- name: Download text code
  git:
    repo: https://github.com/stevetasticsteve/text_interlinear
    dest: "/code/texts"
    version: master
    force: yes
    
- name: Install text script dependencies
  pip:
    requirements: "/code/texts/requirements.txt"
    virtualenv: "/code/texts/venv"
    virtualenv_command: python3 -m venv
    
- name: Set text script settings
  copy:
    src: "interlinear_settings.py"
    dest: "/code/texts/settings.py"
    mode: "0755"
    owner: "{{ user }}"
    
- name: Schedule text update
  cron:
    name: Texts update
    user: www-data
    state: present
    job: "/bin/bash /code/texts/run_interlinear.sh >/dev/null 2>&1"
    minute: "*/10"
    
- name: Symlink the source xml directory
  # This symlink will enable code to access the xml file stored in nextcloud (when process runs as root or www-data)
  file:
      src: "{{ external_storage[0].mount_point}}/docker-data/volumes/nextcloud_data/_data/data/steve/files/Team Share/texts/"
      dest: /code/texts/xml
      owner: "www-data"
      group: "www-data"
      mode: "0755"
      state: link
      force: yes
