- name: Download Lexicon code
  git:
    repo: https://github.com/stevetasticsteve/Lexicon
    dest: "/code/lexicon"
    version: master
    force: yes

- name: Create Lexicon virtual environment
  pip:
    requirements: "/code/lexicon/requirements.txt"
    virtualenv: "/code/lexicon/venv"
    virtualenv_command: python3 -m venv

- name: Install system dependency
  apt:
      name: libxslt-dev
      state: present

- name: Symlink the source dictionary
  file:
      src: "{{ external_storage[0].mount_point}}/docker-data/volumes/nextcloud_data/_data/data/steve/files/Team Share/lexicon/Kovol_lexicon.ods"
      dest: /code/lexicon/lexicon.ods
      owner: "www-data"
      group: "www-data"
      mode: "0755"
      state: link
      force: yes

- name: Symlink the source verb dictionary
  file:
      src: "{{ external_storage[0].mount_point}}/docker-data/volumes/nextcloud_data/_data/data/steve/files/Team Share/lexicon/Kovol_verbs.ods"
      dest: /code/lexicon/Kovol_verbs.ods
      owner: "www-data"
      group: "www-data"
      mode: "0755"
      state: link
      force: yes
    
- name: Set Lexicon config
  copy:
    src: lexicon_config.py
    dest: "/code/lexicon/lexicon_config.py"
    mode: "0755"
    owner: "{{ user }}"

- name: Schedule Lexicon update
  cron:
    name: Lexicon update
    state: present
    job: "bash /code/lexicon/run_lexicon.sh"
    minute: "20"
    hour: "0"
