- name: Set hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    mode: "0644"

- name: Configure docker nextcloud and CLAHub
  include_tasks: docker.yml

# - name: Copy static html folder
#   include_tasks: static_html.yml

- name: Create code folder
  file:
    state: directory
    path: "/code/logs"
    mode: "0777"
    owner: "{{ user }}"

- name: Install Lexicon
  include_tasks: lexicon.yml

- name: Install Interlinear
  include_tasks: interlinear.yml

- name: Set backup
  include_tasks: backup.yml

- name: Set up server check
  include_tasks: health_check.yml