- name: Create /html 
  file:
    path: /html
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "0777"
    recurse: yes
    
- name: Fill html folder
  copy:
    src: html
    mode: "0777"
    owner: "www-data"
    group: www-data
    dest: /

- name: Create Bootstrap folder
  file:
    path: "/html/static/bootstrap"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
        
- name: Extract bootstrap
  unarchive:
    src: bootstrap.zip
    dest: "/html/static/bootstrap"
    owner: "{{ user }}"
    mode: "0755"

- name: Create Jquery folder
  file:
    path: "/html/static/jquery"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
        
- name: Extract jquery
  unarchive:
    src: jquery.zip
    dest: "/html/static/jquery"
    owner: "{{ user }}"
    mode: "0755"

- name: Create fontawesome folder
  file:
    path: "/html/static/fontawesome"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
        
- name: Extract fontawesome
  unarchive:
    src: fontawesome.zip
    dest: "/html/static/fontawesome"
    owner: "{{ user }}"
    mode: "0755"