- name: Create html folder
  copy:
    src: html
    mode: "0777"
    owner: "{{ user }}"
    dest: /

- name: Create Bootstrap folder
  file:
    path: "/html/static/bootstrap"
    state: directory
    mode: "0777"
    owner: "{{ user }}"
        
- name: Extract bootstrap
  unarchive:
    src: bootstrap.zip
    dest: "/html/static/bootstrap"
    owner: "{{ user }}"
    mode: "0777"

- name: Create Jquery folder
  file:
    path: "/html/static/jquery"
    state: directory
    mode: "0777"
    owner: "{{ user }}"
        
- name: Extract jquery
  unarchive:
    src: jquery.zip
    dest: "/html/static/jquery"
    owner: "{{ user }}"
    mode: "0777"