- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Steve's PPAs
  apt_repository:
    repo: "{{item}}"
    state: present
    update_cache: True
  loop:
   "{{steve_workstation_ppa}}"

- name: Check if rpi-imager installed
  command: dpkg-query -W rpi-imager
  register: rpi_check
  failed_when: rpi_check.rc > 1
  changed_when: rpi_check.rc == 1

- name: Download rpi-imager
  get_url:
   url: https://downloads.raspberrypi.org/imager/imager_1.5_amd64.deb
   dest: /tmp/imager_1.5_amd64.deb
   mode: "0644"
  when: rpi_check.rc == 1

- name: Install rpi
  apt:
   deb: /tmp/imager_1.5_amd64.deb
  when: rpi_check.rc == 1


- name: Install Steve's packages
  apt:
    name: "{{steve_workstation_packages}}"

- name: Add user to docker group
  user:
   name: "{{user}}"
   groups: docker
   append: yes

- name: Install Steve's classic snaps
  snap:
    name: "{{steve_workstation_classic_snaps}}"
    classic: yes

- name: Copy desktop wallpaper
  copy:
   src: ./files/dragon_orbit.jpg
   dest: /usr/share/backgrounds/dragon_orbit.jpg

- name: Set Steve's desktop background
  become_user: "{{user}}"
  dconf:
   key: "/org/gnome/desktop/background/picture-uri"
   value: "'file:///usr/share/backgrounds/dragon_orbit.jpg'"
   
- name: Remove Ubuntu dock
  apt:
    name: gnome-shell-extension-ubuntu-dock
    state: absent


- name: Add Gerdine user
  user:
   name: gerdine
   password: "{{gerdine_user_password}}"
   groups: 
   append: yes
   update_password: on_create
