- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add Docker PPA
  apt_repository:
    repo: "deb https://download.docker.com/linux/raspbian {{ansible_lsb.codename}} stable"
    state: present
    update_cache: True

- name: Install Docker
  apt:
    name: "{{item}}"
    state: present
    update_cache: True
  loop:
   - docker-ce
   - docker-ce-cli
   - containerd.io
   - libffi-dev
   - libssl-dev
   - python3-dev
   - python3
   - python3-pip

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Add user to docker group
  user:
   name: "{{user}}"
   groups: docker
   append: yes

# - name: Create docker-data folder if external storage is used
#   file:
#     path: "{{ HD_mount }}/docker-data"
#     state: directory
#     mode: "0664"
#     group: docker
#   when: HD_uid is defined

# - name: Change docker volume location
#   template:
#     src: daemon.json
#     dest: /etc/docker
#     owner: "{{user}}"
#     group: docker
#     mode: "0644"
#   notify: 
#     - restart Docker
#   when: HD_uid is defined
