html_folder = "/html/texts"
code_folder = "/code/texts"
audio_folder = "audio"
xml_folder = "xml"
word_list_file = "/html/lexicon/word_list.csv"
log_file = "/code/logs/interlinear.html"
error_log_file = "/code/logs/interlinear_error.html"
