- name: Turn on night light
  become_user: "{{user}}"
  dconf:
   key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
   value: "true"

- name: Set Papirus themes
  become_user: "{{user}}"
  dconf:
   key: "/org/gnome/desktop/interface/icon-theme"
   value: "'Papirus'"
  when: ansible_distribution == 'Ubuntu'