- name: Update OS
  apt:
    upgrade: dist

- name: Add PPAs
  apt_repository:
    repo: "{{item}}"
    state: present
    update_cache: True
  loop:
   "{{workstation_ppa}}"

- name: Add Papirus ppa
  apt_repository:
   repo: ppa:papirus/papirus
   state: present
   update_cache: True
  when: ansible_distribution == 'Ubuntu'

- name: Install papirus icons
  apt:
   name: papirus-icon-theme
  when: ansible_distribution == 'Ubuntu'

- name: Install base packages
  apt:
    name: "{{workstation_packages}}"

- name: Install base snap packages
  snap:
    name: "{{workstation_snap_packages}}"

- name: Install classic snaps
  snap:
    name: "{{workstation_classic_snaps}}"
    classic: yes

- name: Install Authy Beta snap
  snap:
    name: authy
    channel: beta

- name: Check if tagspaces installed
  command: dpkg-query -W tagspaces
  register: tagspaces_check
  failed_when: tagspaces_check.rc > 1
  changed_when: tagspaces_check.rc == 1

- name: Download tagspaces
  get_url:
   url: "https://www.tagspaces.org/downloads/tagspaces-amd64.deb"
   dest: /tmp/tagspaces-amd64.deb
   mode: "0644"
  when: tagspaces_check.rc == 1

- name: Install tagspaces
  apt:
   deb: /tmp/tagspaces-amd64.deb
  when: tagspaces_check.rc == 1

- name: Check if zoom installed
  command: dpkg-query -W zoom
  register: zoom_check
  failed_when: zoom_check.rc > 1
  changed_when: zoom_check.rc == 1

- name: Download zoom
  get_url:
   url: "https://zoom.us/client/latest/zoom_amd64.deb"
   dest: /tmp/zoom-amd64.deb
   mode: "0644"
  when: zoom_check.rc == 1

- name: Install zoom
  apt:
   deb: /tmp/zoom-amd64.deb
  when: zoom_check.rc == 1

- name: Create template files
  file:
    path: "/home/{{user}}/Templates/{{item}}"
    state: touch
    owner: "{{user}}"
    mode: "0664"
  loop:
   "{{workstation_templates}}"

- name: Enable firewall
  ufw:
   state: enabled
   
- name: Add user to KVM group
  user:
   name: "{{user}}"
   groups: kvm, libvirt
   append: yes
  loop:

- include: gnome.yml

