- name: Copy desktop wallpaper
  copy:
   src: ./files/Crocus_Wallpaper_by_Roy_Tanck.jpg
   dest: /usr/share/backgrounds/Crocus_Wallpaper_by_Roy_Tanck.jpg

- name: Set Gerdine's desktop background
  become_user: "{{user}}"
  dconf:
   key: "/org/gnome/desktop/background/picture-uri"
   value: "'file:///usr/share/backgrounds/Crocus_Wallpaper_by_Roy_Tanck.jpg'"

- name: Install Gerdine's packages
  apt:
    name: "{{gerdine_workstation_packages}}"

- name: Allow SSH over firewall
  ufw:
   state: enabled
   rule: allow
   name: ssh

- name: Enable Steve's SSH key
  authorized_key:
    user: "{{user}}"
    state: present
    key: ./files/steve_ssh.pub