- name: Create a pi hole
  hosts: bracknell_pi
  become: True

  tasks:
    - name: disable ssh login for user pi
      lineinfile:
        dest=/etc/ssh/sshd_config
        line="DenyUsers pi"
        state=present
      notify:
        - Restart SSH

    - name: remove pi user
      user:
        name: pi
        state: absent
        remove: yes

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: reloaded