version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1001:1001
    ports:
      - 80:8096
    volumes:
      - /home/steve/.jellyfin-conf:/config:z
      - /home/steve/.jellyfin-cache:/cache:z
      - /home/steve/Videos:/media:z
    restart: "unless-stopped"


