# First playbook to run on a fresh rasbperry pi: Asks for new username and password, creates it, enables SSH key login
# and deletes pi user.
---
- hosts: server_pi
  vars_files:
    - ~/Documents/Computing/Linux_deployment/Ansible/ssh_keys.yml
  vars_prompt:
    - name: new_username
      prompt: "Enter a new username"
    - name: new_password
      prompt: "Enter a new password"
  become: true

  tasks:
    - name: Set up admin user
      user:
        name: "{{ new_username }}"
        shell: /bin/bash
        password: "{{ new_password }}"
        groups: sudo
        append: yes
    - name: Authorize SSH keys
      authorized_key:
        user: kovol
        key: "{{ ssh_keys }}"
        state: present

    - name: disable ssh login for user pi
      lineinfile:
        dest=/etc/ssh/sshd_config
        line="DenyUsers pi"
        state=present
      notify:
       - Restart SSH

    - name: remove pi user
      user:
        name: pi
        state: absent
        remove: yes

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: reloaded
...
